kind: Service
apiVersion: v1
metadata:
  name: captureorderack-lb
spec:
  selector:
    app: captureorderack
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer