apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: eventlistener-deployment
  labels:
    app: eventlistener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eventlistener
  template:
    metadata:
      labels:
        app: eventlistener
    spec:
      containers:
      - name: eventlistener
        image: shanepeckham/eventhublistenerack:v5
        env:
        - name: TEAMNAME
          value: 'team2-ct'
        - name: MONGOHOST
          value: 'mongodb://prodmongo-mongodb.default.svc.cluster.local'
        - name: EVENTHUBCONNSTRING
          value: 'Endpoint=sb://orderfulfillment.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=RsO8TJ4yJMMP5dlyIlIjjAUOHtbj3Kjv+vTzC0qJc8A='
        - name: EVENTHUBPATH
          value: 'orderfulfillment'
        - name: PROCESSENDPOINT
          value: 'http://orderfulfillment-lb.default.svc.cluster.local:8080/v1/order'
        - name: PARTITIONKEY
          value: '0'
        ports:
        - containerPort: 8080