apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: orderfulfillment-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefile