apiVersion: v1
kind: PersistentVolume
metadata:
  name: orderfulfillment-v
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: orders
    readOnly: false
  claimRef:
    namespace: default
    name: orderfulfillment-claim