apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: b3JkZXJmdWxmaWxsbWVudA==
  azurestorageaccountkey: Qk1JaHRPTk9FbUdhUEk0UTZCdWZ6OGZ3ZjlScDBYTzZzUW91ajNaQ2lWL2FJWmw0VjI5bDV3cG1La1dNQmZtOFlCTWI2RFVDYVdpeHB6SlhrL3JyQUE9PQ==