apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: orderfulfillment-deployment
  labels:
    app: orderfulfillment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orderfulfillment
  template:
    metadata:
      labels:
        app: orderfulfillment
    spec:
      containers:
      - name: orderfulfillment
        image: shanepeckham/fulfillorderack:v5
        volumeMounts:
        - name: orders
          mountPath: /orders
        env:
        - name: TEAMNAME
          value: 'team2-ct'
        - name: MONGOHOST
          value: 'mongodb://sillymonkeysorders:PTXq1qzwbufLjlI2oaRCyiNhq0mB3lXiZP7bUmqHAa1g5wefLu1WrBszcQmq2AdgOYr6qxQ9MlmtsIFGZ3cG5w==@sillymonkeysorders.documents.azure.com:10255/?ssl=true'
        ports:
        - containerPort: 8080
      volumes:
      - name: orders
        persistentVolumeClaim:
          claimName: orderfulfillment-claim