kind: Service
apiVersion: v1
metadata:
  name: orderfulfillment-lb
spec:
  selector:
    app: orderfulfillment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP